name: '${project.name}'
version: '${version}'
main: '${project.groupId}.${project.artifactId}.${project.artifactId}'
api-version: 1.13
depend: [ BlueMap ]
authors: [ TechnicJelle ]
description: '${project.description}'
website: '${project.url}'
